experiment:
  yolo_version: "v8"
  model_size: n # n, s, m, l, x
  model_task: detection # only detection is supported yet
  experiment_name: # optional
  dataset_path: data
  model_type: engine # pt, engine
