[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jet"
version = "1.0.0"
description = "Joint Evaluation of TensorRT Backends for YOLOv8."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Ali Al-Bustami", email = "abustami@umich.edu" },
  { name = "Humberto Ruiz-Ochoa", email = "hruiz@umich.edu" },
]


dependencies = [
  "logdir>=0.13.0",
  "matplotlib>=3.10.5",
  "onnx>=1.19.0",
  "pandas>=2.3.2",
  "pydantic>=2.11.7",
  "typer>=0.16.1",
  "ultralytics>=8.3.189",
]

[project.scripts]
jet = "jet.apps.cli:app"

# dev-only dependencies
[dependency-groups]
dev = [
  "black>=25.1.0",
  "flake8>=7.3.0",
  "isort>=6.0.1",
  "pre-commit>=4.3.0",
]


[tool.setuptools.packages.find]
include = ["jet*"]

# tell uv to install dev deps by default
[tool.uv]
default-groups = ["dev"]

[tool.black]
line-length = 79
include = "\\.pyi?$"
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tmp
  | \.vscode
  | \.*.egg-info
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
